### PR TITLE
Update to latest holo-nixpkgs build-dna process

### PR DESCRIPTION
**Pull request by pjkundert**
o Move to top-level Cargo.toml

### CODE REVIEW

**Comment by pjkundert** [comment]
A few things:
- Move this from `holochain` to `Holo-Host`?
- Rename to `communities` from `hylo-holo-dnas`?

**Comment by pjkundert** [comment]
Hey, @lorenjohnson  -- we're considering renaming this to `holo-communities`, and moving it to `Holo-Host` team, and "un-forking" it from `Hylozoic/hylo-holo-dnas`...

What do you think of that?

**Review by willemolding — APPROVED** [review]

**Comment by willemolding** [comment]
> Hey, @lorenjohnson -- we're considering renaming this to `holo-communities`, and moving it to `Holo-Host` team, and "un-forking" it from `Hylozoic/hylo-holo-dnas`...
> 
> What do you think of that?

Very happy for this to move. Just make sure you let us know when you move it so we can update remotes

**Comment by lorenjohnson** [comment]
Yes, let's do it. That all sounds great and `holo-communities` makes sense.

**Review by lorenjohnson — APPROVED** [review]

**Pull request merged**
